pipeline:
  build:
    image: nixos/nix
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    commands:
      - nix --log-format raw -L build .#docker.x86_64-linux
  deploy:
    image: nixos/nix
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    secrets: [ fly_api_token ]
    commands:
      - nix --log-format raw -L run .#deploy
