base_url = "https://greg.burd.me"
title = "greg@burd.me"
description = "Greg Burd's words, please ignore."
default_language = "en"

compile_sass = true
build_search_index = false
generate_feeds = true
ignored_content = [
    "**/_*.{png,svg}",  # unoptimized images
]

# theme is inlined
# theme = "apollo"

taxonomies = [
    { name = "tags" },
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
extra_syntaxes_and_themes = [
    "extra/syntax/"
]
render_emoji = true
external_links_target_blank = true
external_links_no_referrer = true

[extra]
favicon = "/image/favicon.svg"
stylesheets = []

fonts = [
    { path = "ia-writer-quattro", name = "iAWriterQuattroS" },
    { path = "ibm-plex-mono", name = "IBMPlexMono" },
    { path = "inria-sans", name = "InriaSans" }
]

menu = [
    { name = "/posts", url = "@/posts/_index.md" },
    { name = "/projects", url = "@/projects.md" },
    { name = "/about", url = "@/about.md" },
    { name = "git", url = "https://git.burd.me/greg", external = true },
]

me_links = [
    { name = "keybase.io", url = "https://keybase.io/gregburd" },
    { name = "github", url = "https://github.com/gburd" },
    { name = "fediverse", url = "https://mastodon.social/@gregburd" },
    # { name = "fediverse", url = "https://hachyderm.io/@gregburd" },
    { name = "repl.it", url = "https://replit.com/@gregburd" },
    { name = "twitter", url = "https://twitter.com/gregburd" },
    { name = "linkedin", url = "https://linkedin.com/in/gregburd" },
    { name = "lobste.rs", url = "https://lobste.rs/u/gregburd" },
    { name = "news.ycombinator.com", url = "https://news.ycombinator.com/user?id=gregburd" },
]

