base_url = "https://mat.services"
title = "mat.services"
description = "the personal website of matthew ess"

default_language = "en"

compile_sass = true

build_search_index = false

generate_feed = true

theme = "apollo"

[markdown]
highlight_code = true
render_emoji = false
external_links_target_blank = true
external_links_no_referrer = true

[extra]
theme = "auto"
favicon = "/favicon.svg"
stylesheets = []

use_cdn = true
cdns = [
    "https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.min.css",
    "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard-std-dynamic-subset.min.css",
    "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/variable/pretendardvariable-std.min.css",
    "https://cdn.jsdelivr.net/gh/codex-src/iA-Fonts@master/iA%20Writer%20Quattro/Webfonts/index.min.css",
    "https://cdn.jsdelivr.net/gh/codex-src/iA-Fonts@master/iA%20Writer%20Quattro/Variable/index.min.css",
]

menu = [
    { name = "/posts", url = "/posts" },
    { name = "/projects", url = "/projects" },
    { name = "/about", url = "/about" },
    { name = "git", url = "https://git.mat.services/explore/repos", external = true },
]

